export enum RoleCode {
    ADMIN = 'ADMIN',
    USER = 'USER',
    AGENT = 'AGENT',
    MANAGER = 'MANAGER',
    BASIC_USER = 'BASIC_USER',
    ADVANCED_USER = 'ADVANCED_USER',
    PRO_USER = 'PROFESSIONAL_USER'
}